name: π““ Daily Log
description: μ¤λ ν• μ‘μ—… μ •λ¦¬ λ° κ°„λ‹¨ νκ³ 
title: '[Daily] YYYY-MM-DD'
labels: ['daily']
body:
  - type: textarea
    id: today
    attributes:
      label: μ¤λ ν• μΌ
      description: μ¤λ μ§„ν–‰ν• μ‘μ—…μ„ λ‚μ—΄
      placeholder: |
        - μ΄μ ν…ν”λ¦Ώ κµ¬μ„±
        - μµλ… λ‹‰λ„¤μ„ μ ν‹Έ κµ¬ν„
        - PR λ¦¬λ·°
    validations:
      required: true

  - type: textarea
    id: learn
    attributes:
      label: λ°°μ΄ μ  / κ³ λ―Όν• μ 
      description: μƒλ΅ μ•κ² λ κ²ƒ, κ³ λ―Όν• μ„¤κ³„ ν¬μΈνΈ
      placeholder: |
        - λ‹‰λ„¤μ„ μ λ‹ν¬μ— μ§‘μ°©ν•  ν•„μ” μ—†μ
        - μ΄μλ¥Ό μ»¤λ®¤λ‹ν‹°μ²λΌ μ“°λ” κ² λ” ν¨μ¨μ 
    validations:
      required: false

  - type: textarea
    id: retrospect
    attributes:
      label: νκ³ 
      description: μν• μ , μ•„μ‰¬μ΄ μ , λ‚΄μΌ ν•  κ²ƒ
      placeholder: |
        π‘ μν• μ :
        π‘ μ•„μ‰¬μ΄ μ :
        π‘‰ λ‚΄μΌ ν•  μΌ:
    validations:
      required: false
